import type { Pool, PoolClient } from "pg";

export async function runIpoCycle(pool:Pool,now=new Date()):Promise<{opened:number;allocated:number;listed:number}>{let opened=0,allocated=0,listed=0;const due=await pool.query<{id:string;status:string}>("SELECT id,status FROM ipo_campaigns WHERE (status='announced' AND subscription_starts_at<=$1) OR (status='subscription' AND subscription_ends_at<=$1) OR (status='allocated' AND listing_at<=$1) ORDER BY created_at",[now]);for(const row of due.rows){const c=await pool.connect();try{await c.query("BEGIN");const lock=await c.query<any>("SELECT * FROM ipo_campaigns WHERE id=$1 FOR UPDATE",[row.id]);const ipo=lock.rows[0];if(!ipo){await c.query("COMMIT");continue}if(ipo.status==='announced'&&ipo.subscription_starts_at<=now){await c.query("UPDATE ipo_campaigns SET status='subscription',updated_at=now() WHERE id=$1",[ipo.id]);opened++;}else if(ipo.status==='subscription'&&ipo.subscription_ends_at<=now){await allocate(c,ipo);allocated++;}else if(ipo.status==='allocated'&&ipo.listing_at<=now){await c.query("UPDATE ipo_campaigns SET status='listed',updated_at=now() WHERE id=$1",[ipo.id]);await c.query("UPDATE companies SET status='listed',updated_at=now() WHERE id=$1",[ipo.company_id]);await c.query("UPDATE stocks SET is_trading_halted=false,listing_status='normal',listing_status_reason=NULL,updated_at=now() WHERE company_id=$1 AND symbol=$2",[ipo.company_id,ipo.symbol]);await c.query("INSERT INTO notifications(user_id,event_type,title,body) SELECT user_id,'ipo.listed',$2,$3 FROM ipo_subscriptions WHERE campaign_id=$1",[ipo.id,`${ipo.symbol} 상장`,`공모주 ${ipo.symbol} 거래가 시작되었습니다.`]);listed++;}await c.query("COMMIT");}catch(e){await c.query("ROLLBACK");throw e;}finally{c.release();}}return{opened,allocated,listed};}

async function allocate(c:PoolClient,ipo:any){const subscriptions=await c.query<{id:string;user_id:string;requested_quantity:string;reserved_amount:string}>("SELECT * FROM ipo_subscriptions WHERE campaign_id=$1 ORDER BY created_at,id FOR UPDATE",[ipo.id]);const total=subscriptions.rows.reduce((s,r)=>s+BigInt(r.requested_quantity),0n),offered=BigInt(ipo.offered_shares);let allocations=subscriptions.rows.map(r=>({row:r,quantity:total<=offered?BigInt(r.requested_quantity):BigInt(r.requested_quantity)*offered/total}));let assigned=allocations.reduce((s,r)=>s+r.quantity,0n);for(const item of allocations){if(assigned>=min(total,offered))break;if(item.quantity<BigInt(item.row.requested_quantity)){item.quantity+=1n;assigned+=1n;}}
 const stock=await c.query<{id:string}>(`INSERT INTO stocks(company_id,symbol,total_shares,free_float_shares,treasury_shares,current_price,previous_close,reference_price,is_trading_halted,listing_status,listing_status_reason,listing_review_ends_at) VALUES($1,$2,$3,$4,($3::bigint-$4::bigint),$5,$5,$5,true,'halted','IPO 배정 완료·상장 대기',$6) RETURNING id`,[ipo.company_id,ipo.symbol,ipo.total_shares,assigned.toString(),ipo.offer_price,ipo.listing_at]);const stockId=stock.rows[0]!.id;
 for(const item of allocations){const cost=item.quantity*BigInt(ipo.offer_price);await c.query("UPDATE users SET cash=cash-$2,reserved_cash=reserved_cash-$3,updated_at=now() WHERE id=$1 AND cash>=$2 AND reserved_cash>=$3",[item.row.user_id,cost.toString(),item.row.reserved_amount]);await c.query("UPDATE ipo_subscriptions SET allocated_quantity=$2,reserved_amount=0,updated_at=now() WHERE id=$1",[item.row.id,item.quantity.toString()]);if(item.quantity>0n)await c.query("INSERT INTO holdings(user_id,stock_id,quantity,cost_basis) VALUES($1,$2,$3,$4)",[item.row.user_id,stockId,item.quantity.toString(),cost.toString()]);await c.query("INSERT INTO notifications(user_id,event_type,title,body) VALUES($1,'ipo.allocated',$2,$3)",[item.row.user_id,`${ipo.symbol} 공모주 배정`,`${item.quantity.toString()}주가 배정되었습니다.`]);}
 await c.query("UPDATE companies SET status='ipo',updated_at=now() WHERE id=$1",[ipo.company_id]);await c.query("UPDATE ipo_campaigns SET status='allocated',updated_at=now() WHERE id=$1",[ipo.id]);}
function min(a:bigint,b:bigint){return a<b?a:b}
