import { BadRequestException, Body, Controller, Get, Injectable, NotFoundException, Param, ParseUUIDPipe, Patch, Post, Query, UseGuards } from "@nestjs/common";
import type { PoolClient } from "pg";
import { z } from "zod";
import { AccessTokenGuard, AdminGuard, CurrentUser, type AccessPrincipal } from "./auth.guard.js";
import { DatabaseService } from "./database.service.js";

const pageSchema = z.object({ q: z.string().trim().max(100).optional(), limit: z.coerce.number().int().min(1).max(200).default(50), offset: z.coerce.number().int().min(0).default(0) });
const accountSchema = z.object({ isActive: z.boolean() }).strict();
const assetSchema = z.object({ delta: z.string().regex(/^-?\d{1,30}$/), reason: z.string().trim().min(3).max(500) }).strict();
const stockSchema = z.object({ companyId: z.uuid(), symbol: z.string().trim().toUpperCase().regex(/^[A-Z][A-Z0-9]{1,9}$/), totalShares: positive(), freeFloatShares: nonnegative(), currentPrice: positive(), tickSize: positive() }).strict();
const stockEditSchema = z.object({ symbol: z.string().trim().toUpperCase().regex(/^[A-Z][A-Z0-9]{1,9}$/).optional(), companyName: z.string().trim().min(1).max(100).optional(), sectorId: z.uuid().optional() }).strict();
const financeSchema = z.object({ cash: nonnegative().optional(), debt: nonnegative().optional(), revenue: nonnegative().optional(), operatingProfit: z.string().regex(/^-?\d{1,30}$/).optional(), netProfit: z.string().regex(/^-?\d{1,30}$/).optional(), bookValue: nonnegative().optional(), growthRateBps: z.number().int().min(-10_000).max(100_000).optional(), riskScore: z.number().int().min(0).max(1_000).optional() }).strict();
const haltSchema = z.object({ halted: z.boolean(), reason: z.string().trim().min(3).max(500) }).strict();
const eventSchema = z.object({ eventType: z.string().trim().min(1).max(50), title: z.string().trim().min(1).max(100), description: z.string().trim().min(1).max(1000), fairValueImpactBps: z.number().int().min(-10_000).max(10_000).default(0), demandImpactBps: z.number().int().min(-10_000).max(10_000).default(0), liquidityImpactBps: z.number().int().min(-10_000).max(10_000).default(0), volatilityImpactBps: z.number().int().min(-10_000).max(10_000).default(0), durationMinutes: z.number().int().min(1).max(43_200).optional() }).strict();
const regimeSchema = z.object({ regime: z.enum(["strong_bull", "bull", "sideways", "bear", "fear", "recovery"]), strength: z.number().int().min(-100).max(100), breadthBps: z.number().int().min(0).max(10_000), averageReturnBps: z.number().int().min(-100_000).max(100_000), reason: z.string().trim().min(3).max(500) }).strict();
const sectorSchema = z.object({ strength: z.number().int().min(-100).max(100), averageReturnBps: z.number().int().min(-100_000).max(100_000), reason: z.string().trim().min(3).max(500) }).strict();
const settingSchema = z.object({ key: z.enum(["spot_fee_bps", "leverage_limit", "market_maker_refresh_ms"]), value: z.number().int().nonnegative(), reason: z.string().trim().min(3).max(500) }).strict().superRefine((v, c) => { if (v.key === "spot_fee_bps" && v.value > 1_000) c.addIssue({ code: "custom", message: "수수료 상한 초과" }); if (v.key === "leverage_limit" && ![1,2,3,5,10,20,50,100].includes(v.value)) c.addIssue({ code: "custom", message: "허용되지 않은 레버리지" }); if (v.key === "market_maker_refresh_ms" && (v.value < 1_000 || v.value > 3_600_000)) c.addIssue({ code: "custom", message: "갱신 간격 범위 오류" }); });
const seasonSchema = z.object({ name: z.string().trim().min(1).max(100) }).strict();
const etfSchema = stockSchema.omit({ freeFloatShares: true }).extend({ trackedUserId: z.uuid(), freeFloatShares: positive() }).strict();
const stabilityActionSchema = z.object({
  action: z.enum(["reselect_trend","set_tier","recalculate_fair_value","rebuild_market_maker","start_distress","end_distress","trigger_circuit_breaker","inspect_price_path"]),
  tier: z.enum(["BLUE_CHIP","GIANT","MEGA","LARGE","MID","SMALL","DELIST_RISK"]).optional(),
  reason: z.string().trim().min(3).max(500),
}).strict().superRefine((v,c)=>{if(v.action==="set_tier"&&!v.tier)c.addIssue({code:"custom",message:"수동 티어가 필요합니다."});});

@Injectable()
export class AdminService {
  constructor(private readonly database: DatabaseService) {}

  async users(input: unknown) {
    const page = parse(pageSchema, input);
    return (await this.database.pool.query(`SELECT id,email,username,nickname,role,cash,reserved_cash,is_active,created_at FROM users WHERE is_system=false AND ($1::text IS NULL OR email ILIKE '%'||$1||'%' OR username ILIKE '%'||$1||'%' OR nickname ILIKE '%'||$1||'%') ORDER BY created_at DESC LIMIT $2 OFFSET $3`, [page.q ?? null, page.limit, page.offset])).rows;
  }
  async setAccount(adminId: string, userId: string, input: unknown) {
    const value = parse(accountSchema, input); return this.tx(async (client) => {
      const user = await client.query("UPDATE users SET is_active=$2,updated_at=now() WHERE id=$1 AND is_system=false RETURNING id,is_active", [userId, value.isActive]); if (!user.rows[0]) throw new NotFoundException("사용자를 찾을 수 없습니다.");
      if (!value.isActive) await client.query("UPDATE refresh_tokens SET revoked_at=now() WHERE user_id=$1 AND revoked_at IS NULL", [userId]);
      await audit(client, adminId, "admin.user_status", "user", userId, value); return user.rows[0];
    });
  }
  async adjustAsset(adminId: string, userId: string, input: unknown) {
    const value = parse(assetSchema, input); const delta = BigInt(value.delta); if (delta === 0n) throw new BadRequestException("0원 조정은 허용하지 않습니다.");
    return this.tx(async (client) => { const result = await client.query("UPDATE users SET cash=cash+$2,updated_at=now() WHERE id=$1 AND is_system=false AND cash+$2>=reserved_cash AND cash+$2>=0 RETURNING id,cash,reserved_cash", [userId, delta.toString()]); if (!result.rows[0]) throw new BadRequestException("조정 후 자산이 예약금보다 작거나 사용자가 없습니다."); await audit(client, adminId, "admin.asset_adjust", "user", userId, value); return result.rows[0]; });
  }
  async createStock(adminId: string, input: unknown) {
    const v = parse(stockSchema, input); if (BigInt(v.freeFloatShares) > BigInt(v.totalShares)) throw new BadRequestException("유통주식은 총주식수를 초과할 수 없습니다.");
    return this.tx(async (c) => { if (!(await c.query("SELECT id FROM companies WHERE id=$1", [v.companyId])).rows[0]) throw new NotFoundException("기업을 찾을 수 없습니다."); const r = await c.query("INSERT INTO stocks (company_id,symbol,total_shares,free_float_shares,current_price,previous_close,reference_price,tick_size) VALUES ($1,$2,$3,$4,$5,$5,$5,$6) RETURNING *", [v.companyId,v.symbol,v.totalShares,v.freeFloatShares,v.currentPrice,v.tickSize]); await audit(c,adminId,"admin.stock_create","stock",r.rows[0].id,v); return r.rows[0]; });
  }
  async editStock(adminId: string, stockId: string, input: unknown) {
    const v=parse(stockEditSchema,input); if (!Object.keys(v).length) throw new BadRequestException("변경값이 없습니다."); return this.tx(async(c)=>{ const locked=await c.query<{ company_id:string }>("SELECT company_id FROM stocks WHERE id=$1 FOR UPDATE",[stockId]); if(!locked.rows[0]) throw new NotFoundException("종목을 찾을 수 없습니다."); if(v.symbol) await c.query("UPDATE stocks SET symbol=$2,updated_at=now() WHERE id=$1",[stockId,v.symbol]); if(v.companyName) await c.query("UPDATE companies SET name=$2,updated_at=now() WHERE id=$1",[locked.rows[0].company_id,v.companyName]); if(v.sectorId) await c.query("UPDATE companies SET sector_id=$2,updated_at=now() WHERE id=$1",[locked.rows[0].company_id,v.sectorId]); await audit(c,adminId,"admin.stock_edit","stock",stockId,v); return (await c.query("SELECT s.*,c.name AS company_name,c.sector_id FROM stocks s JOIN companies c ON c.id=s.company_id WHERE s.id=$1",[stockId])).rows[0]; });
  }
  async updateFinance(adminId:string,companyId:string,input:unknown){const v=parse(financeSchema,input);if(!Object.keys(v).length)throw new BadRequestException("변경값이 없습니다.");return this.tx(async c=>{const r=await c.query(`UPDATE companies SET cash=COALESCE($2,cash),debt=COALESCE($3,debt),revenue=COALESCE($4,revenue),operating_profit=COALESCE($5,operating_profit),net_profit=COALESCE($6,net_profit),book_value=COALESCE($7,book_value),growth_rate_bps=COALESCE($8,growth_rate_bps),risk_score=COALESCE($9,risk_score),updated_at=now() WHERE id=$1 RETURNING *`,[companyId,v.cash??null,v.debt??null,v.revenue??null,v.operatingProfit??null,v.netProfit??null,v.bookValue??null,v.growthRateBps??null,v.riskScore??null]);if(!r.rows[0])throw new NotFoundException("기업을 찾을 수 없습니다.");await audit(c,adminId,"admin.company_finance","company",companyId,v);return r.rows[0];});}
  async halt(adminId:string,stockId:string,input:unknown){const v=parse(haltSchema,input);return this.tx(async c=>{const r=await c.query("UPDATE stocks SET is_trading_halted=$2,updated_at=now() WHERE id=$1 RETURNING *",[stockId,v.halted]);if(!r.rows[0])throw new NotFoundException("종목을 찾을 수 없습니다.");await audit(c,adminId,"admin.trading_halt","stock",stockId,v);return r.rows[0];});}
  async createEvent(adminId:string,companyId:string,input:unknown){const v=parse(eventSchema,input);return this.tx(async c=>{const r=await c.query(`INSERT INTO corporate_events (company_id,event_type,title,description,fair_value_impact_bps,demand_impact_bps,liquidity_impact_bps,volatility_impact_bps,ends_at,created_by_user_id) SELECT $1,$2,$3,$4,$5,$6,$7,$8,CASE WHEN $9::int IS NULL THEN NULL ELSE now()+($9||' minutes')::interval END,$10 WHERE EXISTS(SELECT 1 FROM companies WHERE id=$1) RETURNING *`,[companyId,v.eventType,v.title,v.description,v.fairValueImpactBps,v.demandImpactBps,v.liquidityImpactBps,v.volatilityImpactBps,v.durationMinutes??null,adminId]);if(!r.rows[0])throw new NotFoundException("기업을 찾을 수 없습니다.");await audit(c,adminId,"admin.company_event","company",companyId,v);return r.rows[0];});}
  async setRegime(adminId:string,input:unknown){const v=parse(regimeSchema,input);return this.tx(async c=>{await c.query("UPDATE market_regimes SET ended_at=now() WHERE ended_at IS NULL");const r=await c.query("INSERT INTO market_regimes (regime,strength,breadth_bps,average_return_bps,metadata) VALUES ($1,$2,$3,$4,jsonb_build_object('adminOverride',true,'reason',$5::text)) RETURNING *",[v.regime,v.strength,v.breadthBps,v.averageReturnBps,v.reason]);await audit(c,adminId,"admin.market_regime","market",r.rows[0].id,v);return r.rows[0];});}
  async setSector(adminId:string,sectorId:string,input:unknown){const v=parse(sectorSchema,input);return this.tx(async c=>{if(!(await c.query("SELECT id FROM sectors WHERE id=$1",[sectorId])).rows[0])throw new NotFoundException("섹터를 찾을 수 없습니다.");const r=await c.query("INSERT INTO sector_states (sector_id,strength,average_return_bps,updated_at) VALUES ($1,$2,$3,now()) ON CONFLICT(sector_id) DO UPDATE SET strength=$2,average_return_bps=$3,updated_at=now() RETURNING *",[sectorId,v.strength,v.averageReturnBps]);await audit(c,adminId,"admin.sector_state","sector",sectorId,v);return r.rows[0];});}
  async orders(input:unknown){const p=parse(pageSchema,input);return(await this.database.pool.query("SELECT o.*,s.symbol,u.username FROM orders o JOIN stocks s ON s.id=o.stock_id JOIN users u ON u.id=o.user_id WHERE ($1::text IS NULL OR s.symbol ILIKE '%'||$1||'%' OR u.username ILIKE '%'||$1||'%') ORDER BY o.created_at DESC LIMIT $2 OFFSET $3",[p.q??null,p.limit,p.offset])).rows;}
  async trades(input:unknown){const p=parse(pageSchema,input);return(await this.database.pool.query("SELECT t.*,s.symbol,bu.username AS buyer,su.username AS seller FROM trades t JOIN stocks s ON s.id=t.stock_id JOIN users bu ON bu.id=t.buyer_user_id JOIN users su ON su.id=t.seller_user_id WHERE ($1::text IS NULL OR s.symbol ILIKE '%'||$1||'%' OR bu.username ILIKE '%'||$1||'%' OR su.username ILIKE '%'||$1||'%') ORDER BY t.created_at DESC LIMIT $2 OFFSET $3",[p.q??null,p.limit,p.offset])).rows;}
  async stockStability(input:unknown){const p=parse(pageSchema,input);return(await this.database.pool.query(`SELECT s.id,s.symbol,c.name company_name,s.current_price,(s.current_price*s.total_shares)::bigint current_market_cap,
    s.stability_market_cap,s.market_cap_ema_24h,s.market_cap_ema_7d,s.stability_tier,s.trend_regime,s.trend_ends_at,s.daily_change_bps,
    s.target_daily_volatility_bps,s.fundamental_fair_value,CASE WHEN s.fundamental_fair_value>0 THEN ((s.current_price-s.fundamental_fair_value)*10000/s.fundamental_fair_value)::int END fair_value_gap_bps,
    s.distress_score,s.distress_components,s.listing_status,s.circuit_breaker_until,
    CASE s.stability_tier WHEN 'BLUE_CHIP' THEN jsonb_build_object('downBps',-600,'upBps',800) WHEN 'GIANT' THEN jsonb_build_object('downBps',-1200,'upBps',1500)
      WHEN 'MEGA' THEN jsonb_build_object('downBps',-1500,'upBps',2000) WHEN 'LARGE' THEN jsonb_build_object('downBps',-2000,'upBps',2800)
      WHEN 'MID' THEN jsonb_build_object('downBps',-2800,'upBps',3800) WHEN 'SMALL' THEN jsonb_build_object('downBps',-3500,'upBps',5000) ELSE jsonb_build_object('downBps',-4500,'upBps',6500) END daily_band,
    (SELECT count(*)::int FROM orders o JOIN market_makers mm ON mm.user_id=o.user_id WHERE o.stock_id=s.id AND o.status IN ('open','partially_filled')) market_maker_quote_depth,
    (SELECT jsonb_agg(x ORDER BY x.started_at DESC) FROM (SELECT event_type,change_5m_bps,change_30m_bps,started_at,ended_at FROM price_guard_events WHERE stock_id=s.id ORDER BY started_at DESC LIMIT 5)x) recent_price_guards
    FROM stocks s JOIN companies c ON c.id=s.company_id WHERE s.asset_type='common' AND ($1::text IS NULL OR s.symbol ILIKE '%'||$1||'%' OR c.name ILIKE '%'||$1||'%') ORDER BY current_market_cap DESC LIMIT $2 OFFSET $3`,[p.q??null,p.limit,p.offset])).rows;}
  async stabilityAction(adminId:string,stockId:string,input:unknown){const v=parse(stabilityActionSchema,input);return this.tx(async c=>{const locked=await c.query<any>("SELECT s.*,c.cash,c.debt,c.net_profit,c.book_value FROM stocks s JOIN companies c ON c.id=s.company_id WHERE s.id=$1 FOR UPDATE OF s",[stockId]);const s=locked.rows[0];if(!s)throw new NotFoundException("종목을 찾을 수 없습니다.");let result:unknown;
    if(v.action==="reselect_trend")result=(await c.query("UPDATE stocks SET trend_ends_at=now(),updated_at=now() WHERE id=$1 RETURNING *",[stockId])).rows[0];
    else if(v.action==="set_tier")result=(await c.query("UPDATE stocks SET stability_tier=$2,stability_tier_entered_at=now(),stability_tier_candidate=NULL,stability_tier_candidate_since=NULL,updated_at=now() WHERE id=$1 RETURNING *",[stockId,v.tier])).rows[0];
    else if(v.action==="recalculate_fair_value")result=(await c.query(`UPDATE stocks SET fundamental_fair_value=GREATEST(1,(GREATEST(0,$2::bigint)+GREATEST(0,$3::bigint)*8+GREATEST(0,$4::bigint-$5::bigint)/2)/GREATEST(1,total_shares)),fair_value_updated_at=now(),updated_at=now() WHERE id=$1 RETURNING *`,[stockId,s.book_value,s.net_profit,s.cash,s.debt])).rows[0];
    else if(v.action==="rebuild_market_maker"){await c.query("UPDATE market_makers SET last_refreshed_at=NULL,updated_at=now() WHERE stock_id=$1",[stockId]);result={stockId,queued:true};}
    else if(v.action==="start_distress")result=(await c.query("UPDATE stocks SET listing_status='distress_review',listing_status_reason=$2,listing_review_ends_at=now()+interval '7 days',updated_at=now() WHERE id=$1 RETURNING *",[stockId,v.reason])).rows[0];
    else if(v.action==="end_distress")result=(await c.query("UPDATE stocks SET listing_status='normal',listing_status_reason=NULL,listing_review_ends_at=NULL,is_trading_halted=false,updated_at=now() WHERE id=$1 RETURNING *",[stockId])).rows[0];
    else if(v.action==="trigger_circuit_breaker"){result=(await c.query("UPDATE stocks SET is_trading_halted=true,circuit_breaker_until=now()+interval '1 minute',circuit_breaker_reason=$2,circuit_breaker_count=circuit_breaker_count+1,updated_at=now() WHERE id=$1 RETURNING *",[stockId,v.reason])).rows[0];await c.query("INSERT INTO price_guard_events(stock_id,event_type,triggered_by,reference_price,observed_price,protected_price,metadata) VALUES($1,'admin_circuit_breaker','admin',$2,$2,$2,jsonb_build_object('reason',$3::text,'adminId',$4::text))",[stockId,s.current_price,v.reason,adminId]);}
    else result=(await c.query(`SELECT $1::uuid stock_id,(SELECT count(*)::int FROM candles WHERE stock_id=$1 AND opened_at>=now()-interval '48 hours') candle_count,(SELECT min(low) FROM candles WHERE stock_id=$1 AND opened_at>=now()-interval '48 hours') low_48h,(SELECT max(high) FROM candles WHERE stock_id=$1 AND opened_at>=now()-interval '48 hours') high_48h,(SELECT count(*)::int FROM price_guard_events WHERE stock_id=$1 AND started_at>=now()-interval '48 hours') guard_count`,[stockId])).rows[0];
    await audit(c,adminId,`admin.stability.${v.action}`,"stock",stockId,v);return result;});}
  async suspicious(){const pairs=await this.database.pool.query(`SELECT buyer_user_id,seller_user_id,count(*)::int AS trade_count,sum(price*quantity)::bigint AS value FROM trades WHERE created_at>=now()-interval '24 hours' GROUP BY buyer_user_id,seller_user_id HAVING count(*)>=10 ORDER BY value DESC LIMIT 200`);const security=await this.database.pool.query("SELECT * FROM security_events WHERE created_at>=now()-interval '7 days' ORDER BY created_at DESC LIMIT 200");return{repeatedCounterparties:pairs.rows,securityEvents:security.rows};}
  async cancelMna(adminId:string,id:string,reason:string){if(reason.trim().length<3)throw new BadRequestException("취소 사유가 필요합니다.");return this.tx(async c=>{const r=await c.query<{attacker_user_id:string;committed_cash:string;spent_cash:string;status:string}>("SELECT * FROM mna_campaigns WHERE id=$1 FOR UPDATE",[id]);const m=r.rows[0];if(!m||!["tendering","proxy_vote"].includes(m.status))throw new BadRequestException("취소 가능한 M&A가 아닙니다.");await c.query("UPDATE users SET reserved_cash=reserved_cash-($2-$3),updated_at=now() WHERE id=$1",[m.attacker_user_id,m.committed_cash,m.spent_cash]);await c.query(`UPDATE holdings h SET reserved_quantity=h.reserved_quantity-x.quantity,updated_at=now() FROM (SELECT shareholder_user_id,sum(quantity)::bigint quantity FROM mna_tender_offers WHERE campaign_id=$1 AND status='reserved' GROUP BY shareholder_user_id) x, mna_campaigns mc WHERE mc.id=$1 AND h.user_id=x.shareholder_user_id AND h.stock_id=mc.stock_id`,[id]);await c.query("UPDATE mna_tender_offers SET status='released',updated_at=now() WHERE campaign_id=$1 AND status='reserved'",[id]);const out=await c.query("UPDATE mna_campaigns SET status='cancelled',resolved_at=now(),result=jsonb_build_object('reason',$2::text,'cancelledBy',$3::text),updated_at=now() WHERE id=$1 RETURNING *",[id,reason,adminId]);await audit(c,adminId,"admin.mna_cancel","mna_campaign",id,{reason});return out.rows[0];});}
  async pauseStrategy(adminId:string,id:string,reason:string){if(reason.trim().length<3)throw new BadRequestException("정지 사유가 필요합니다.");return this.tx(async c=>{const r=await c.query("UPDATE strategies SET paused_from_status=status,status='PAUSED',updated_at=now() WHERE id=$1 AND status IN ('PAPER','LIVE_VIRTUAL') RETURNING *",[id]);if(!r.rows[0])throw new BadRequestException("실행 중인 전략이 아닙니다.");await audit(c,adminId,"admin.strategy_pause","strategy",id,{reason});return r.rows[0];});}
  async setting(adminId:string,input:unknown){const v=parse(settingSchema,input);return this.tx(async c=>{const r=await c.query("INSERT INTO system_settings(key,value,updated_by_user_id,updated_at) VALUES($1,jsonb_build_object('value',$2::int),$3,now()) ON CONFLICT(key) DO UPDATE SET value=EXCLUDED.value,updated_by_user_id=$3,updated_at=now() RETURNING *",[v.key,v.value,adminId]);if(v.key==='market_maker_refresh_ms')await c.query("UPDATE market_makers SET refresh_interval_ms=$1,updated_at=now()",[v.value]);await audit(c,adminId,"admin.setting", "system_setting",v.key,v);return r.rows[0];});}
  async startSeason(adminId:string,input:unknown){const v=parse(seasonSchema,input);return this.tx(async c=>{if((await c.query("SELECT id FROM seasons WHERE is_active=true")).rows[0])throw new BadRequestException("활성 시즌이 이미 있습니다.");const r=await c.query("INSERT INTO seasons(name,starts_at,is_active,started_by_user_id) VALUES($1,now(),true,$2) RETURNING *",[v.name,adminId]);await audit(c,adminId,"admin.season_start","season",r.rows[0].id,v);return r.rows[0];});}
  async endSeason(adminId:string,id:string){return this.tx(async c=>{const r=await c.query("UPDATE seasons SET is_active=false,ends_at=now(),ended_by_user_id=$2 WHERE id=$1 AND is_active=true RETURNING *",[id,adminId]);if(!r.rows[0])throw new BadRequestException("활성 시즌이 아닙니다.");await audit(c,adminId,"admin.season_end","season",id,{});return r.rows[0];});}
  async createEtf(adminId:string,input:unknown){const v=parse(etfSchema,input);if(BigInt(v.freeFloatShares)>BigInt(v.totalShares))throw new BadRequestException("유통주식은 총주식수를 초과할 수 없습니다.");return this.tx(async c=>{const snap=await c.query<{eligible_asset_value:string}>("SELECT uv.eligible_asset_value FROM user_valuation_snapshots uv JOIN valuation_cycles vc ON vc.id=uv.cycle_id WHERE uv.user_id=$1 AND vc.status='completed' ORDER BY vc.completed_at DESC LIMIT 1",[v.trackedUserId]);if(!snap.rows[0]||BigInt(snap.rows[0].eligible_asset_value)<=0n)throw new BadRequestException("추종 사용자의 완료 valuation snapshot이 필요합니다.");const s=await c.query("INSERT INTO stocks(company_id,symbol,total_shares,free_float_shares,current_price,previous_close,reference_price,tick_size,asset_type) VALUES($1,$2,$3,$4,$5,$5,$5,$6,'user_etf') RETURNING *",[v.companyId,v.symbol,v.totalShares,v.freeFloatShares,v.currentPrice,v.tickSize]);await c.query("INSERT INTO etf_products(stock_id,tracked_user_id,base_eligible_asset_value,base_price) VALUES($1,$2,$3,$4)",[s.rows[0].id,v.trackedUserId,snap.rows[0].eligible_asset_value,v.currentPrice]);await audit(c,adminId,"admin.etf_create","stock",s.rows[0].id,v);return s.rows[0];});}
  private async tx<T>(run:(client:PoolClient)=>Promise<T>):Promise<T>{const c=await this.database.pool.connect();try{await c.query("BEGIN");const r=await run(c);await c.query("COMMIT");return r;}catch(e){await c.query("ROLLBACK");throw e;}finally{c.release();}}
}

@Controller("admin") @UseGuards(AccessTokenGuard,AdminGuard)
export class AdminController {
  constructor(private readonly admin:AdminService){}
  @Get("users") users(@Query() q:unknown){return this.admin.users(q)}
  @Patch("users/:id/account") account(@CurrentUser()u:AccessPrincipal,@Param("id",new ParseUUIDPipe())id:string,@Body()b:unknown){return this.admin.setAccount(u.userId,id,b)}
  @Post("users/:id/assets") asset(@CurrentUser()u:AccessPrincipal,@Param("id",new ParseUUIDPipe())id:string,@Body()b:unknown){return this.admin.adjustAsset(u.userId,id,b)}
  @Post("stocks") stock(@CurrentUser()u:AccessPrincipal,@Body()b:unknown){return this.admin.createStock(u.userId,b)}
  @Patch("stocks/:id") editStock(@CurrentUser()u:AccessPrincipal,@Param("id",new ParseUUIDPipe())id:string,@Body()b:unknown){return this.admin.editStock(u.userId,id,b)}
  @Post("stocks/:id/halt") halt(@CurrentUser()u:AccessPrincipal,@Param("id",new ParseUUIDPipe())id:string,@Body()b:unknown){return this.admin.halt(u.userId,id,b)}
  @Patch("companies/:id/finance") finance(@CurrentUser()u:AccessPrincipal,@Param("id",new ParseUUIDPipe())id:string,@Body()b:unknown){return this.admin.updateFinance(u.userId,id,b)}
  @Post("companies/:id/events") event(@CurrentUser()u:AccessPrincipal,@Param("id",new ParseUUIDPipe())id:string,@Body()b:unknown){return this.admin.createEvent(u.userId,id,b)}
  @Post("market/regime") regime(@CurrentUser()u:AccessPrincipal,@Body()b:unknown){return this.admin.setRegime(u.userId,b)}
  @Post("sectors/:id/state") sector(@CurrentUser()u:AccessPrincipal,@Param("id",new ParseUUIDPipe())id:string,@Body()b:unknown){return this.admin.setSector(u.userId,id,b)}
  @Get("orders") orders(@Query()q:unknown){return this.admin.orders(q)} @Get("trades") trades(@Query()q:unknown){return this.admin.trades(q)} @Get("suspicious") suspicious(){return this.admin.suspicious()}
  @Get("stocks/stability") stability(@Query()q:unknown){return this.admin.stockStability(q)}
  @Post("stocks/:id/stability-action") stabilityAction(@CurrentUser()u:AccessPrincipal,@Param("id",new ParseUUIDPipe())id:string,@Body()b:unknown){return this.admin.stabilityAction(u.userId,id,b)}
  @Post("mna/:id/cancel") cancelMna(@CurrentUser()u:AccessPrincipal,@Param("id",new ParseUUIDPipe())id:string,@Body()b:{reason?:string}){return this.admin.cancelMna(u.userId,id,b.reason??"")}
  @Post("strategies/:id/pause") pause(@CurrentUser()u:AccessPrincipal,@Param("id",new ParseUUIDPipe())id:string,@Body()b:{reason?:string}){return this.admin.pauseStrategy(u.userId,id,b.reason??"")}
  @Post("settings") setting(@CurrentUser()u:AccessPrincipal,@Body()b:unknown){return this.admin.setting(u.userId,b)}
  @Post("seasons") season(@CurrentUser()u:AccessPrincipal,@Body()b:unknown){return this.admin.startSeason(u.userId,b)} @Post("seasons/:id/end") endSeason(@CurrentUser()u:AccessPrincipal,@Param("id",new ParseUUIDPipe())id:string){return this.admin.endSeason(u.userId,id)}
  @Post("etfs") etf(@CurrentUser()u:AccessPrincipal,@Body()b:unknown){return this.admin.createEtf(u.userId,b)}
}

async function audit(c:PoolClient,actor:string,action:string,targetType:string,targetId:string,metadata:unknown){await c.query("INSERT INTO audit_logs(actor_user_id,action,target_type,target_id,metadata) VALUES($1,$2,$3,$4,$5::jsonb)",[actor,action,targetType,targetId,JSON.stringify(metadata)])}
function positive(){return z.string().regex(/^\d{1,30}$/).refine(v=>BigInt(v)>0n)} function nonnegative(){return z.string().regex(/^\d{1,30}$/)}
function parse<T>(schema:z.ZodType<T>,input:unknown):T{const r=schema.safeParse(input);if(!r.success)throw new BadRequestException({message:"관리자 입력이 올바르지 않습니다.",issues:r.error.issues});return r.data}
