import { BadRequestException, Body, Controller, Get, Injectable, Post, UseGuards } from "@nestjs/common";
import { z } from "zod";
import { AccessTokenGuard, AdminGuard, CurrentUser, type AccessPrincipal } from "./auth.guard.js";
import { DatabaseService } from "./database.service.js";

const createSchema=z.object({companyId:z.uuid(),symbol:z.string().trim().toUpperCase().regex(/^[A-Z][A-Z0-9]{1,9}$/),description:z.string().trim().min(10).max(2000),offerPrice:positive(),totalShares:positive(),offeredShares:positive(),subscriptionStartsAt:z.iso.datetime(),subscriptionEndsAt:z.iso.datetime(),listingAt:z.iso.datetime()}).strict();
const subscribeSchema=z.object({campaignId:z.uuid(),quantity:positive()}).strict();

@Injectable() export class IpoService{
 constructor(private readonly database:DatabaseService){}
 async list(){return(await this.database.pool.query(`SELECT ic.*,c.name company_name,COALESCE(sum(isub.requested_quantity),0)::bigint subscribed_quantity FROM ipo_campaigns ic JOIN companies c ON c.id=ic.company_id LEFT JOIN ipo_subscriptions isub ON isub.campaign_id=ic.id GROUP BY ic.id,c.name ORDER BY ic.created_at DESC`)).rows;}
 async create(adminId:string,input:unknown){const v=parse(createSchema,input);if(BigInt(v.offeredShares)>BigInt(v.totalShares))throw new BadRequestException("공모주식은 총주식수를 초과할 수 없습니다.");const start=new Date(v.subscriptionStartsAt),end=new Date(v.subscriptionEndsAt),listing=new Date(v.listingAt);if(!(start<end&&end<=listing))throw new BadRequestException("IPO 일정 순서가 올바르지 않습니다.");const c=await this.database.pool.connect();try{await c.query("BEGIN");const r=await c.query(`INSERT INTO ipo_campaigns(company_id,symbol,description,offer_price,total_shares,offered_shares,subscription_starts_at,subscription_ends_at,listing_at,created_by_user_id) SELECT $1,$2,$3,$4,$5,$6,$7,$8,$9,$10 WHERE EXISTS(SELECT 1 FROM companies WHERE id=$1 AND status='private') RETURNING *`,[v.companyId,v.symbol,v.description,v.offerPrice,v.totalShares,v.offeredShares,start,end,listing,adminId]);if(!r.rows[0])throw new BadRequestException("비상장 기업만 IPO를 생성할 수 있습니다.");await c.query("INSERT INTO audit_logs(actor_user_id,action,target_type,target_id,metadata) VALUES($1,'admin.ipo_create','ipo_campaign',$2,$3::jsonb)",[adminId,r.rows[0].id,JSON.stringify(v)]);await c.query("COMMIT");return r.rows[0];}catch(e){await c.query("ROLLBACK");throw e;}finally{c.release();}}
 async subscribe(userId:string,input:unknown){const v=parse(subscribeSchema,input);const quantity=BigInt(v.quantity);const c=await this.database.pool.connect();try{await c.query("BEGIN");const campaign=await c.query<{offer_price:string;status:string;subscription_starts_at:Date;subscription_ends_at:Date}>("SELECT * FROM ipo_campaigns WHERE id=$1 FOR UPDATE",[v.campaignId]);const ipo=campaign.rows[0],now=new Date();if(!ipo||ipo.status!=="subscription"||now<ipo.subscription_starts_at||now>=ipo.subscription_ends_at)throw new BadRequestException("현재 청약 가능한 IPO가 아닙니다.");const existing=await c.query<{reserved_amount:string}>("SELECT reserved_amount FROM ipo_subscriptions WHERE campaign_id=$1 AND user_id=$2 FOR UPDATE",[v.campaignId,userId]);const reserve=quantity*BigInt(ipo.offer_price),prior=BigInt(existing.rows[0]?.reserved_amount??"0"),delta=reserve-prior;const user=await c.query("UPDATE users SET reserved_cash=reserved_cash+$2,updated_at=now() WHERE id=$1 AND cash-reserved_cash >= $2 RETURNING id",[userId,delta.toString()]);if(!user.rows[0])throw new BadRequestException("청약 예약금이 부족합니다.");const r=await c.query("INSERT INTO ipo_subscriptions(campaign_id,user_id,requested_quantity,reserved_amount) VALUES($1,$2,$3,$4) ON CONFLICT(campaign_id,user_id) DO UPDATE SET requested_quantity=$3,reserved_amount=$4,updated_at=now() RETURNING *",[v.campaignId,userId,quantity.toString(),reserve.toString()]);await c.query("COMMIT");return r.rows[0];}catch(e){await c.query("ROLLBACK");throw e;}finally{c.release();}}
}

@Controller("ipos") export class IpoController{constructor(private readonly service:IpoService){}@Get()list(){return this.service.list()}@Post()@UseGuards(AccessTokenGuard,AdminGuard)create(@CurrentUser()u:AccessPrincipal,@Body()b:unknown){return this.service.create(u.userId,b)}@Post("subscribe")@UseGuards(AccessTokenGuard)subscribe(@CurrentUser()u:AccessPrincipal,@Body()b:unknown){return this.service.subscribe(u.userId,b)}}
function positive(){return z.string().regex(/^\d{1,30}$/).refine(v=>BigInt(v)>0n)}function parse<T>(s:z.ZodType<T>,i:unknown):T{const r=s.safeParse(i);if(!r.success)throw new BadRequestException({message:"IPO 입력이 올바르지 않습니다.",issues:r.error.issues});return r.data}
