"use client";
import { FormEvent, useCallback, useEffect, useState } from "react";
import AppShell from "./AppShell";
import { api } from "../lib/api";

export function MnaList() {
  const [items, setItems] = useState<any[]>();
  const [toast, setToast] = useState("");
  const load = useCallback(() => api<any[]>("/api/mna").then(setItems).catch((e) => setToast(e.message)), []);
  useEffect(() => { void load(); }, [load]);
  async function create(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const form = new FormData(event.currentTarget); try { await api("/api/mna", { method: "POST", body: JSON.stringify({ companyId: form.get("companyId"), idempotencyKey: crypto.randomUUID(), offerPrice: form.get("offerPrice"), committedCash: form.get("committedCash"), tenderDurationMinutes: 1440, proxyDurationMinutes: 1440 }) }); setToast("M&A 캠페인을 개시했습니다."); await load(); } catch (e: any) { setToast(e.message); } }
  return <AppShell><div className="page-head"><div><span className="eyebrow">CONTROL MARKET</span><h1>M&A 시장</h1><p>20% 이상 지분과 약정 현금으로 공개매수·위임장 경쟁을 개시합니다.</p></div></div><div className="grid"><section className="panel third"><h2>적대적 M&A 개시</h2><form className="form" onSubmit={create}><label>기업 ID<input name="companyId" required/></label><label>공개매수가<input name="offerPrice" type="number" min="1" required/></label><label>약정 현금<input name="committedCash" type="number" min="1" required/></label><button>자격 확인·개시</button></form></section><section className="panel" style={{ gridColumn: "span 8" }}><h2>캠페인</h2>{!items ? <div className="state">불러오는 중입니다.</div> : items.length === 0 ? <div className="state">캠페인이 없습니다.</div> : <table><thead><tr><th>기업</th><th>Symbol</th><th>공격자</th><th>공개매수가</th><th>상태</th></tr></thead><tbody>{items.map((item) => <tr key={item.id}><td><a href={`/mna/${item.id}`}>{item.company_name}</a></td><td>{item.symbol}</td><td>{item.attacker_nickname}</td><td>{item.offer_price}</td><td>{item.status}</td></tr>)}</tbody></table>}</section></div>{toast && <div className="toast" onClick={() => setToast("")}>{toast}</div>}</AppShell>;
}

export function MnaDetail({ id }: { id: string }) {
  const [detail, setDetail] = useState<any>();
  const [toast, setToast] = useState("");
  const load = useCallback(() => api(`/api/mna/${id}`).then(setDetail).catch((e) => setToast(e.message)), [id]);
  useEffect(() => { void load(); }, [load]);
  async function submit(event: FormEvent<HTMLFormElement>, path: string, build: (form: FormData) => unknown) { event.preventDefault(); const form = new FormData(event.currentTarget); try { await api(`/api/mna/${id}/${path}`, { method: "POST", body: JSON.stringify(build(form)) }); setToast("M&A 행동을 기록했습니다."); await load(); } catch (e: any) { setToast(e.message); } }
  return <AppShell>{!detail ? <div className="state">캠페인을 불러오는 중입니다.</div> : <><div className="page-head"><div><span className="eyebrow">{detail.status}</span><h1>M&A 캠페인</h1><p>공개매수가 {detail.offer_price} · 공격 점수 {detail.attacker_score} · 방어 점수 {detail.defender_score}</p></div></div><div className="grid"><section className="panel third"><h2>공개매수 응모</h2><form className="form" onSubmit={(e) => submit(e, "tenders", (f) => ({ quantity: f.get("quantity") }))}><label>수량<input name="quantity" type="number" min="1" required/></label><button>주식 예약·응모</button></form></section><section className="panel third"><h2>의결권 지지</h2><form className="form" onSubmit={(e) => submit(e, "support", (f) => ({ side: f.get("side") }))}><label>진영<select name="side"><option value="attacker">공격자</option><option value="defender">방어자</option></select></label><button>의결권 snapshot</button></form></section><section className="panel third"><h2>공방 행동</h2><form className="form" onSubmit={(e) => submit(e, "actions", (f) => ({ idempotencyKey: crypto.randomUUID(), side: f.get("side"), actionType: f.get("actionType"), cashAmount: f.get("cashAmount") || "0" }))}><label>진영<select name="side"><option value="attacker">공격자</option><option value="defender">방어자</option></select></label><label>행동<select name="actionType"><option value="add_cash">현금 추가</option><option value="proxy_solicitation">위임장 권유</option><option value="buyback">자사주 매입</option><option value="white_knight">백기사</option><option value="poison_pill">포이즌 필</option></select></label><label>현금<input name="cashAmount" type="number" min="0" defaultValue="0"/></label><button>행동 실행</button></form></section><section className="panel"><h2>공개매수·지지·행동 기록</h2><pre>{JSON.stringify({ tenders: detail.tenders, supports: detail.supports, actions: detail.actions }, null, 2)}</pre></section></div></>}{toast && <div className="toast" onClick={() => setToast("")}>{toast}</div>}</AppShell>;
}
